name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main
      - dev-docker
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        id: build-and-push
        run: |
          # Determine the image tag based on the branch
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          IMAGE_TAG=$BRANCH_NAME

          # Construct the full image name
          IMAGE_FULL_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG
          echo "Building image: $IMAGE_FULL_NAME"

          # Build the Docker image
          docker build \
            --file ${{ env.DOCKERFILE_PATH }} \
            --tag "$IMAGE_FULL_NAME" \
            .

          # Push the Docker image to GitHub Packages
          docker push "$IMAGE_FULL_NAME"

          echo "::set-output name=image::$IMAGE_FULL_NAME"