name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and Push Docker Image
        id: build-and-push
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT  # Store the image name for later use (optional)

      - name: Latest Tag (Optional)
        if: github.ref == 'refs/heads/main' #Only add "latest" tag on main branch
        run: |
          docker pull ${{ steps.build-and-push.outputs.image }}
          docker tag ${{ steps.build-and-push.outputs.image }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
